<a href="https://colab.research.google.com/github/wxmlong2012/learn-transformer/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

In [ ]:
x = torch.randn(3,5)

In [ ]:
print(x)

tensor([[-1.2140, -2.2588,  0.4213,  0.1103, -0.4316],
        [ 0.7114,  1.5222, -1.4440, -0.3811,  1.2212],
        [ 0.3103, -1.0308,  0.5702,  0.5897,  0.4839]])


In [ ]:
torch.__version__

'2.1.0+cu118'

In [5]:
# Example of target with class indices
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()
print(input)
print(target)
print(output)



tensor([[-0.1922,  1.0388, -1.5364, -0.0790, -0.4623],
        [-0.7728,  0.9528, -0.7648, -0.7054, -2.3573],
        [-1.2690, -0.3143,  0.3012, -1.5593,  0.2511]], requires_grad=True)
tensor([3, 3, 0])
tensor(2.1690, grad_fn=<NllLossBackward0>)


In [ ]:

# Example of target with class probabilities
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
output = loss(input, target)
output.backward()